apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: altinnkanal-2
  namespace: alf
  labels:
    team: alf
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 30
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 20
    timeout: 1
  leaderElection: false
  prometheus:
    enabled: true
    path: /internal/prometheus
  istio:
    enabled: false
  {{#if ingresses}}
  ingresses:
    {{#each ingresses}}
    - "{{this}}"
    {{/each}}
  {{/if}}
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 200Mi
  vault:
    enabled: true
