routes:
  - topics:
    - aapen-altinn-oppfolgingsplan-Mottatt
    serviceCode: 2913
    serviceEditionCode: 2
  - topics:
    - aapen-altinn-oppfolgingsplan-Mottatt
    serviceCode: 2913
    serviceEditionCode: 3
  - topics:
    - aapen-altinn-oppfolgingsplan-Mottatt
    serviceCode: 2913
    serviceEditionCode: 4
  - topics:
    - aapen-altinn-oppfolgingsplan-Mottatt
    serviceCode: NavOppfPlan
    serviceEditionCode: rapportering-sykmeldte
# Målekort
  - topics:
    - aapen-altinn-maalekort-Mottatt
    serviceCode: 4711
    serviceEditionCode: 1
# Barnehageliste
  - topics:
    - aapen-altinn-barnehageliste-Mottatt
    serviceCode: 4795
    serviceEditionCode: 1
# Kun brukt i unit test Melding om soning
  - topics:
      - aapen-altinn-soning-Mottatt
    serviceCode: 5152
    serviceEditionCode: 1
