routes:
  - topics:
    - aapen-altinn-bankkontonummer-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 2896
    serviceEditionCode: 87
  - topics:
    - aapen-altinn-oppfolgingsplan-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 2913
    serviceEditionCode: 2
  - topics:
    - aapen-altinn-oppfolgingsplan-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 2913
    serviceEditionCode: 3
  - topics:
    - aapen-altinn-oppfolgingsplan-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 2913
    serviceEditionCode: 4
  - topics:
    - aapen-altinn-oppfolgingsplan-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: NavOppfPlan
    serviceEditionCode: rapportering-sykmeldte
  - topics:
    - privat-altinn-paop-Mottatt
    serviceCode: 9001
    serviceEditionCode: 1
  - topics:
    - aapen-altinn-maalekort-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 4711
    serviceEditionCode: 1
  - topics:
    - aapen-altinn-barnehageliste-Mottatt
    serviceCode: 4795
    serviceEditionCode: 1
# Inntektsskjema
  - topics:
    - aapen-altinn-dokmot-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 4936
    serviceEditionCode: 1
  - topics:
    - aapen-altinn-dokmot-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 4936
    serviceEditionCode: 2
  - topics:
    - aapen-altinn-dokmot-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 4936
    serviceEditionCode: 3
# Melding om unndragelse
  - topics:
    - aapen-altinn-dokmot-Mottatt
    - aapen-altinn-unndragelse-Mottatt
    serviceCode: 5161
    serviceEditionCode: 1
# Melding om soning
  - topics:
    - aapen-altinn-dokmot-Mottatt
    - aapen-altinn-soning-Mottatt
    serviceCode: 5152
    serviceEditionCode: 1
# FTT og BHT-honorarer for IA-virksomheter
  - topics:
    - aapen-altinn-dokmot-Mottatt
    serviceCode: 5111
    serviceEditionCode: 1
# Lønnstilskudd
  - topics:
    - aapen-altinn-dokmot-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 5159
    serviceEditionCode: 1
# Inkluderingstilskudd
  - topics:
    - aapen-altinn-dokmot-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 5212
    serviceEditionCode: 1
# Mentortilskudd
  - topics:
    - aapen-altinn-dokmot-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 5216
    serviceEditionCode: 1
# Varig tilrettelagt arbeid i ordinær virksomhet
  - topics:
    - aapen-altinn-dokmot-Mottatt
    serviceCode: 5224
    serviceEditionCode: 1
# Ekspertbistand
  - topics:
    - aapen-altinn-dokmot-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 5384
    serviceEditionCode: 1
# Refusjonskrav ekspertbistand
  - topics:
    - aapen-altinn-dokmot-Mottatt
    serviceCode: 5453
    serviceEditionCode: 1
# Valg av hyppigere refusjonsutbetaling fra NAV
  - topics:
    - aapen-altinn-hyppigutbetaling-Mottatt
    - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 5546
    serviceEditionCode: 1
# Forsendelse av bedriftsundersøkelse
  - topics:
      - aapen-altinn-bedrundersokelse-Mottatt
      - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 5664
    serviceEditionCode: 1
# Nærmeste leder
  - topics:
      - aapen-altinn-narmeste-leder-Mottatt
      - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 4596
    serviceEditionCode: 1
# TT02 Test inbound
  - topics:
      - aapen-altinn-bedrundersokelse-Mottatt
      - aapen-altinn-pakkutbatch-Mottatt
    serviceCode: 4765
    serviceEditionCode: 4
