routes:
# Barnehageliste
  - topics:
    - aapen-altinn-barnehageliste-Mottatt
    serviceCode: 4795
    serviceEditionCode: 1
# Kun brukt i unit test Melding om soning
  - topics:
      - aapen-altinn-soning-Mottatt
    serviceCode: 5152
    serviceEditionCode: 1
